server:
  host: "0.0.0.0"
  port: "8080"

database:
  host: "db"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "folder_system"
  sslmode: "disable"

jwt:
  access_secret: "secret_access"
  refresh_secret: "secret_refresh"
  access_ttl: 15
  refresh_ttl: 10080

logging:
  level: "debug"
  file: "app.log"

# Database initialization settings
db_init:
  user: "postgres"
  password: "password"
  database: "folder_system"